config/routes.rb
Rorum::Application.routes.draw do

  devise_for :users
  resources :messages

  root 'messages#topic'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  #validates :author, presence: true, length: {minimum: 1}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def response_goodness(operation)
    if operation
      render json: @message
    else
      render status: 500
    end
  end

  def index
    #@messages = Message.all
    render json: Message.all.to_json
  end

=begin
  def new
    @message = Message.new
  end
=end

  def create
    if user_signed_in?
      @message = Message.new(user_id: current_user.id, message: params[:message])#message_params)
      response_goodness(@message.save)
    end
  end

=begin
  def show
    #@message = Message.find(params[:id])
    render json: Message.find(params[:id]).to_json
  end


  def edit
    @message = Message.find(params[:id])
  end
=end

  def update
    if user_signed_in?
      @message = Message.find(params[:id])

      if @message.user_id == current_user.id
        response_goodness(@message.update(message: params[:message]))
      else
        response_goodness(false)
      end
    else
      response_goodness(false)
    end
  end

  def destroy
    if user_signed_in?
      @message = Message.find(params[:id])

      if @message.user_id == current_user.id
        response_goodness(@message.destroy)
      else
        response_goodness(false)
      end
    else
      response_goodness(false)
    end
  end

=begin
private
  def message_params
    params.require(:message).permit(:author, :message)
  end
=end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rorum</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>
	<% if user_signed_in? %>
	  <%= link_to(current_user.email, edit_user_registration_path) %>
	  <%= link_to('logout', destroy_user_session_path, method: :delete) %>
	<% else %>
	  <%= link_to('login', new_user_session_path) %>
	  <%= link_to('registration', new_user_registration_path) %>
	<% end %>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/messages/_message_form.html.erb
<%= form_for @message do |f| %>
  <% if @message.errors.any? %>
    <h2><%= pluralize(@message.errors.count, 'error') %>prohibited this message from being saved:</h2>
    <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>

  <p>
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/messages/edit.html.erb
<h2>Editing message</h2>

<%= render 'message_form' %>

<%= link_to 'back', messages_path %>

app/views/messages/new.html.erb
<h2>Adding message</h2>

<%= render 'message_form' %>

<%= link_to 'back', messages_path %>

app/views/messages/show.html.erb
<p>
	<strong>Author:</strong>
	<%= @message.author %>
</p>

<p>
	<strong>Message:</strong>
	<%= @message.message %>
</p>

<%= link_to 'back', messages_path %>
<%= link_to 'edit', edit_message_path %>

app/views/messages/topic.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div id = "container">
      <div id = "topic"></div>

      <% if user_signed_in? %>
      <form id = "new_message_form">
          <!-- <input class = "new_message author" type = "text" placeholder = "author"> -->
          <textarea class = "new_message body inactive" placeholder = "message"></textarea>
          <button class = "button">send</button>
      </form>
      <% end %>
    </div>

    <script id = "message_template" type="text/template">
      <b><div class = "author"><%%- user.email %></div></b>
      <div class = "body"><%%- message %></div>
      <div class = "controls">
        <b><button class = "edit">edit</button></b>
        <button class = "delete">delete</button>
      </div>
    </script>
    <script id = "edit_message_template" type="text/template">
      <!-- do not remove the wrapping tag -->
      <div>
        <textarea class = "edit_message body"></textarea>
      </div>
    </script>
    <script>
      var MessageModel = Backbone.Model.extend({
        urlRoot: '/messages/'
      })

      var Messages = Backbone.Collection.extend({
        url: '/messages',
        model: MessageModel
      })

      var MessageVeiw = Backbone.View.extend({
        
        template: $('#message_template').html(),
        tagName: 'div',
        className: 'message',

        render: function() {
          var template = _.template(this.template)

          this.$el.html(template(this.model.toJSON()))
          return this
        }
      })

      var Topic = Backbone.View.extend({
        el: $('#topic'),

        initialize: function() {
          this.collection = new Messages()
          this.render_topic()
        },

        render_topic: function() {
          var that = this
          this.collection.fetch()
          this.collection.on('add', function(msg) {
            that.render_message(msg)
          })
        },

        render_message: function(message_model) {
          var message_view = new MessageVeiw({
            model: message_model
          })

          var message_el = message_view.render().el
          this.$el.append(message_el)

          this.message_events(message_model, message_el)

          return message_el
        },

        message_events: function(message_model, message_el) {

          <% if user_signed_in? %>
            $('.delete', message_el).on('click', function(e) {

              message_model.destroy({
                success: function() {
                  $(message_el).animate({height: 0, opacity: 0, padding: 0, margin: 0}, 300, function() {
                    message_el.parentNode.removeChild(message_el)
                  })
                }
              })
            })

            var edit_btn = $('.edit', message_el)

            edit_btn.on('click', function edit(e) {
              var body_div = $('.body', message_el)
              /*$(message_el).find('.author')
              .replaceWith('<input class = "edit_message author" value = "' + author_div.text() + '">')
              $(message_el).find('.body')
              .replaceWith('<textarea class = "edit_message body">' + body_div.text() + '</textarea>')*/
              $('.body', message_el)
              .replaceWith($('.body', $('#edit_message_template').text()).val(body_div.text()))
              edit_btn.text('save')

              edit_btn.off('click')
              edit_btn.on('click', function(e) {

                var body_ta = $('.body', message_el)

                message_model.save({
                  message: body_ta.val()
                }, {
                  success: function() {
                    $('.body', message_el).replaceWith(body_div.text(body_ta.val())[0])
                    edit_btn.text('edit')

                    edit_btn.off('click')
                    edit_btn.on('click', edit)
                  }
                })
              })
            })

            $(message_el).on('mouseover', function() {
              if($('.author', this).text() != '<%= current_user.email %>')
                return

              $('.controls button', this).css('visibility', 'visible')

              $(this).on('mouseout', function() {
                if($('.edit_message', this).length)
                  return

                $('.controls button', this).css('visibility', 'hidden')
              })
            })
          <% end %>
        }
      })

      var topic = new Topic()

      $('#new_message_form .button').on('click', function(e) {
        e.preventDefault()

        var new_message = new MessageModel()
        var message = {
          message: $('#new_message_form .body').val(),
        }

        new_message.save(message, {
          success: function(msg) {
            var creation = $(topic.render_message(new_message))
            var normal_height = creation.height()
            creation.addClass('message_creation')
            .animate({height: normal_height, opacity: 1}, 300, function() {
              creation.removeClass('message_creation')
              .css('height', 'auto')
            })

            $('#new_message_form')[0].reset()
          }
        })
      })


      /* ui events */

      $('#new_message_form .body').on('click', function() {
        $('#new_message_form .body').removeClass('inactive')
        $('#new_message_form .button').css('display', 'block')
      })

      $(document).on('click', function(e) {
        if($(e.target).closest('#new_message_form .body').length)
          return

        $('#new_message_form .body').addClass('inactive')
        $('#new_message_form .button').css('display', 'none')
      })

    </script>
  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
	<body>
		<div style = "width: 700px; margin: 0 auto">
			<div id = "topic"></div>
		</div>

		<script id = "message_template" type="text/template">
			<div style = "margin: 10px; padding: 10px; background-color: #CCCCFF; height: 100px">
				<div><b><%%- author %></b></div>
				<div><%%- message %></div>
				<div><%= link_to 'delete', message_path(message), method: :delete %></div>
			</div>
		</script>
		<script>
			var MessageModel = Backbone.Model.extend({
				urlRoot: '../../messages/'
			})

			var Messages = Backbone.Collection.extend({
				url: '/messages',
				model: MessageModel
			})

			var MessageVeiw = Backbone.View.extend({
				tagName: 'div',
				template: $('#message_template').html(),

				render: function() {
					var template = _.template(this.template)

					this.$el.html(template(this.model.toJSON()))
					return this
				}
			})

			var Topic = Backbone.View.extend({
				el: $('#topic'),

				initialize: function() {
					this.collection = new Messages(/*messages_arr*/)
					this.render_topic()
				},

				render_topic: function() {
					/*_.each(this.collection.models, function(item) {
						console.log('33')
						item.fetch({
							success: function(msg) {
								console.log('fetch succ')
								this.render_message(msg)
							},
							error: function() {
								console.log('fetch err', arguments)
							}
						})
					}, this)*/
					var that = this
					this.collection.fetch()
					this.collection.on('add', function(msg) {
						that.render_message(msg)
					})
				},

				render_message: function(message_model) {
					var message_view = new MessageVeiw({
						model: message_model
					})

					this.$el.append(message_view.render().el)
				}
			})

			new Topic()
		</script>
	</body>
</html>